# Generated by Django 3.1.7 on 2021-05-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=250)),
                ('runs', models.IntegerField(default=0)),
                ('ballsfaced', models.IntegerField(default=0)),
                ('ballsbowled', models.IntegerField(default=0)),
                ('oversbowled', models.FloatField(default=0)),
                ('runsgiven', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('strikerate', models.FloatField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('currentruns', models.IntegerField(default=0)),
                ('bowlavg', models.FloatField(default=None)),
                ('bowlsr', models.FloatField(default=None)),
                ('outs', models.IntegerField(default=0)),
                ('average', models.FloatField(default=None)),
                ('innings', models.IntegerField(default=0)),
                ('threehaul', models.IntegerField(default=0)),
                ('fivehaul', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
    ]
