# Generated by Django 3.1.7 on 2021-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('runs', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('ballsfaced', models.IntegerField(default=0)),
                ('strikerate', models.FloatField(default=0)),
                ('fifties', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('currentruns', models.IntegerField(default=0)),
                ('outs', models.IntegerField(default=0)),
                ('average', models.FloatField(default=None)),
                ('innings', models.IntegerField(default=0)),
            ],
        ),
    ]
